### ISSUE TITLE
Handle any color-space, not just rgb

### ISSUE THREAD

**Issue by caub** [caub/ktree#1]
RGB isn't the best space for visually close colors, so might be worth switching to another system (using https://github.com/caub/color-tf)

ps: when the color coordinates don't range in [0, 255] scale them in it

**Comment by qwhex** [comment]
I recommend CIECAM02, as it's very similar to human color perception. I hope I'll have the time to help with your project as it's an interesting topic for me and my HexaBot project depends on your package ;

**Comment by caub** [comment]
Yes, nice idea, in [color-names](https://github.com/meodai/color-names#closest-named-color) the LAB color-space is suggested, but from what I read in https://en.wikipedia.org/wiki/CIECAM02 this one is even more recent and interesting

I'd just need to know the ranges for each of the 3 dimensions

And I'd also like to add a converter in https://github.com/caub/color-tf (some of the needed functions exist in 
https://github.com/Qix-/color-convert/blob/master/conversions.js and https://github.com/baskerville/ciecam02)
