### ISSUE TITLE
padStart

### ISSUE THREAD

**Issue by qwhex** [caub/ktree#2]
Wouldn't it be nice to include our own implementation of padStart, so we can eradicate the node8+ dependency? If I understand correctly there are no other features you use after node6.

**Comment by caub** [comment]
yes it's easy to put 
```js
if (!String.prototype.padStart) {
  String.prototype.padStart = function(n, c) { return (String(c).repeat(n) + this).slice(0, n)
}
```
I don't like too much to polyfill in libs, because you end up with N polyfill instead of just 1 if the consumer do it, but it's short here

**Comment by caub** [comment]
I've added it for next release
